project:
  type: website
  output-dir: docs
  pre-render:
    - mkdir -p docs/cv
    - quarto typst compile cv/cv.typ docs/cv/cv.pdf
    - quarto typst compile cv/resume.typ docs/cv/resume.pdf
  resources:
    - "talks/**/*.pptx"
    - "talks/**/*.pdf"
    - "books/**/*.pdf"
    - "images/**/*"
    - "videos/**/*"

website:
  title: "Kshitij Duraphe"
  site-url: https://ksd3.github.io
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blog
      - href: research.qmd
        text: Research
      - href: textbooks.qmd
        text: Textbooks
      - href: talks.qmd
        text: Talks
      - href: cv.qmd
        text: Resume/CV
      - href: template.qmd
        text: Build Your Own

format:
  html:
    theme:
      light: default
      dark: darkly
    css: styles.css
    html-math-method: mathml
    toc: true
    toc-location: left
    toc-depth: 3
    toc-expand: 2
    page-layout: article
